name: "Tagged Pre-Release"

on:
  push:
    tags:
      - "v*pre"

jobs:
  tagged-release:
    name: "Tagged Pre-Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            *
